# Generated by Django 5.2.7 on 2025-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_comment_user_alter_contactinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_css',
            field=models.FileField(blank=True, null=True, upload_to='css_uploaded'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_html',
            field=models.FileField(blank=True, null=True, upload_to='html_uploaded'),
        ),
    ]
