# Generated by Django 5.2.7 on 2025-12-16 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_post_user_css_post_user_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_js',
            field=models.FileField(blank=True, null=True, upload_to='js_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['js'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_css',
            field=models.FileField(blank=True, null=True, upload_to='css_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['css'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_html',
            field=models.FileField(blank=True, null=True, upload_to='html_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
    ]
