# Generated by Django 5.2.7 on 2025-12-16 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_post_user_js_alter_post_image_alter_post_user_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_preview',
            field=models.ImageField(null=True, upload_to='images_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
