# Generated by Django 5.2.7 on 2025-12-17 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_post_image_alter_post_site_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_preview',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp'])]),
        ),
    ]
