# Generated by Django 5.2.7 on 2025-12-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_userreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
