# Generated by Django 5.2.7 on 2025-12-26 13:37

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_delete_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='staff_modif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded', validators=[post.models.Post.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_preview',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded', validators=[post.models.Post.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_css',
            field=models.FileField(blank=True, null=True, upload_to='css_uploaded', validators=[post.models.Post.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['css'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_html',
            field=models.FileField(blank=True, null=True, upload_to='html_uploaded', validators=[post.models.Post.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['html'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_js',
            field=models.FileField(blank=True, null=True, upload_to='js_uploaded', validators=[post.models.Post.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['js'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[post.models.Post.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
