# Generated by Django 5.2.7 on 2025-12-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_staff_modif_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='staff_modif',
            new_name='staff_modified',
        ),
    ]
